title: Padmoney Blog - Cobrança Recorrente, Pagamento online e Boletos
email: contato@padmoney.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog do Padmoney com informações sobre pagamentos online, cobrança recorrente, boletos bancários,
  finanças e gestão para ajudar seu negócio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.padmoney.com"
url_signup: "https://www.padmoney.com/signup"
url_site: "https://www.padmoney.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

sass:
  style: compressed

permalink: /:categories/:title:output_ext

paginate: 20

collections:
  category:
    output: true

defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      # path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      body_class: "interno"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - scss
  - run.sh
  - bower.json
  - gruntfile.js
  - package.json
  - package-lock.json
